version: '3.2'
services:
    haproxy:
        container_name: haproxy
        restart: always
        image: mminks/haproxy-docker-logging
        ports:
            - "80:8080"
        volumes:
            - ./haproxy:/usr/local/etc/haproxy
    pwd:
        container_name: pwd
        restart: always
        build:
            context: .
            dockerfile: Dockerfile
            args:
                - http_proxy=http://191.191.29.66:3128
                - https_proxy=http://191.191.29.66:3128
        ports:
            - "3000:3000"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
    l2:
        container_name: l2
        restart: always
        build:
            context: .
            dockerfile: Dockerfile.l2
            args:
                - http_proxy=http://191.191.29.66:3128
                - https_proxy=http://191.191.29.66:3128
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        ports:
            - "8022:22"
            - "8053:53"
            - "443:443"
    docker-cleanup:
        restart: always
        image: quay.io/gitlab/gitlab-runner-docker-cleanup
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        environment:
            - LOW_FREE_SPACE=10G
            - EXPECTED_FREE_SPACE=20G
            - LOW_FREE_FILES_COUNT=1048576
            - EXPECTED_FREE_FILES_COUNT=2097152
            - DEFAULT_TTL=10m
            - USE_DF=1
