version: '3.2'
services:
    haproxy:
        container_name: haproxy
        image: mminks/haproxy-docker-logging
         #build:
        #    context: ./haproxy
        ports:
            - "80:8080"
        volumes:
            - ./haproxy:/usr/local/etc/haproxy
    pwd:
        container_name: pwd
        #image: golang
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "3000:3000"
        #command: /bin/sh -c 'ssh-keygen -N "" -t rsa -f /etc/ssh/ssh_host_rsa_key >/dev/null; cd /go/src/github.com/play-with-docker/play-with-docker; go run api.go -save /pwd/sessions -name l2'
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        #    - $GOPATH/src:/go/src
        #    - sessions:/pwd
    l2:
        container_name: l2
        #image: golang
        build:
            context: .
            dockerfile: Dockerfile.l2
        #command: /bin/sh -c 'ssh-keygen -N "" -t rsa -f /etc/ssh/ssh_host_rsa_key >/dev/null; cd /go/src/github.com/play-with-docker/play-with-docker/router/l2; go run l2.go -ssh_key_path /etc/ssh/ssh_host_rsa_key -name l2 -save /pwd/networks'
        volumes:
        #    - $GOPATH/src:/go/src
            - /var/run/docker.sock:/var/run/docker.sock
        #    - networks:/pwd
        ports:
            - "8022:22"
            - "8053:53"
            - "443:443"
#volumes:
#    sessions:
#    networks:
